name: Validate Renovate Config

on:
  push:
    paths:
      - 'renovate.json'
      - '.github/renovate.json5'
  pull_request:
    paths:
      - 'renovate.json'
      - '.github/renovate.json5'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Renovate Config
        uses: renovatebot/github-action@v40.3.12
        with:
          configurationFile: renovate.json
          token: 'x-access-token:${{ secrets.GITHUB_TOKEN }}'
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_CONFIG_FILE: renovate.json
          RENOVATE_VALIDATE_CONFIG_ONLY: 'true'
